---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Update chache & Full system Update
    apt:
      update_cache: true
      upgrade: dist
      cache_valid_time: 3600
      force_apt_get: true

  - name: Install core packages
    package:
      name: htop

