---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Update chache & Full system Update
    apt:
      update_cache: true
      upgrade: dist
      cache_valid_time: 3600
      force_apt_get: true

  - name: Install core packages
    package:
      name:
        - ssh
        - openssh-server
        - vim
        - git
        - tmux
        - glances
        - ffmpeg
        - gnome-shell-extensions
        - vlc
        - wget
        - curl
        - whois
        - zsh
        - xpad
        - tldr
        - unzip
        - gzip
        - chrome-gnome-shell
        - dconf-editor
        - coreutils
        - avahi-daemon
        - gnome-tweaks
        - neofetch
        - software-properties-common
        - apt-transport-https
        - flameshot
        - xclip

          # - name: Set zsh as the default shell
          #become: true
          #shell: chsh -s /usr/bin/zsh '{{ ansible_env }}'
          #args:
          #executable: /usr/bin/zsh
          #register: chsh_result
      #  changed_when: chsh_result.stdout.find('/usr/bin/zsh') != -1

  - name: Download Google Chrome .deb file
    get_url:
      url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
      dest: "/tmp/google-chrome-stable_current_amd64.deb"
      register: chrome_install_result
        #changed_when: "'google-chrome-stable' in chrome_install_result.stdout"

  - name: Install Google chrome
    command: /usr/bin/dpkg -i /tmp/google-chrome-stable_current_amd64.deb

  - name: Add Microsoft repository key for vscode
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: Add Microsoft repository for vscode
    apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
      state: present
      update_cache: yes

  - name: Install vscode
    package:
      name: code

  - name: Add Ulauncher repository
    command: sudo add-apt-repository ppa:agornostal/ulauncher

  - name: Update apt cache
    command: sudo apt update

  - name: Install Ulauncher
    command: sudo apt install ulauncher

  - name: Clone Vundle.vim repository
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim

  - name: Run command to install Oh My Zsh
    expect:
      command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      responses:
        '(#.*):' : 'yes'

  - name: Run vim command for PluginInstall
    command: vim +PluginInstall +qall


  - name: copy .bashrc file
    copy:
     src: files/bashrc
     dest: '{{ ansible_env.HOME }}/.bashrc'
     owner: '{{ ansible_user }}'
     group: '{{ ansible_user }}'

  - name: copy  .zshrc file
    copy:
     src: files/zshrc
     dest: '{{ ansible_env.HOME}}/.zshrc'
     owner: '{{ ansible_user }}'
     group: '{{ ansible_user }}'


  - name: Copy .vimrc file
    copy:
     src: files/vimrc
     dest: '{{ ansible_env.HOME }}/.vimrc'
     owner: '{{ ansible_user }}'
     group: '{{ ansible_user }}'

  - name: Copy .plugin file
    copy:
     src: files/plugin/plugins.vim
     dest: '{{ ansible_env.HOME }}/.vim/plugins.vim'
     owner: '{{ ansible_user }}'
     group: '{{ ansible_user }}'
