---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Update chache & Full system Update
    apt:
      update_cache: true
      upgrade: dist
      cache_valid_time: 3600
      force_apt_get: true

  - name: Install core packages
    package:
      name:
        - ssh
        - openssh-server
        - vim
        - git
        - tmux
        - glances
        - ffmpeg
        - gnome-shell-extensions
        - vlc
        - wget
        - curl
        - whois
        - zsh
        - xpad
        - tldr
        - unzip
        - gzip
        - chrome-gnome-shell
        - dconf-editor
        - coreutils
        - avahi-daemon
        - gnome-tweaks
        - neofetch
        - software-properties-common
        - apt-transport-https
        - flameshot
        - xclip
        - gnome-shell-extension-prefs

          # - name: Set zsh as the default shell
          #become: true
          #shell: chsh -s /usr/bin/zsh '{{ ansible_env }}'
          #args:
          #executable: /usr/bin/zsh
          #register: chsh_result
      #  changed_when: chsh_result.stdout.find('/usr/bin/zsh') != -1

  - name: Download Google Chrome .deb file
    get_url:
      url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
      dest: "/tmp/google-chrome-stable_current_amd64.deb"
        #register: chrome_install_result
        #changed_when: "'google-chrome-stable' in chrome_install_result.stdout"

  - name: Install Google chrome
    command: /usr/bin/dpkg -i /tmp/google-chrome-stable_current_amd64.deb

  - name: Add Microsoft repository key for vscode
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: Add Microsoft repository for vscode
    apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
      state: present
      update_cache: yes

  - name: Install vscode
    package:
      name: code

  - name: Download Dash to Dock GNOME Shell extension
    uri:
      url: "https://extensions.gnome.org/extension-data/dash-to-dockmicxgx.gmail.com.v71.shell-extension.zip"
      dest: "/tmp/dash-to-dock.zip"
      mode: 0644

  - name: Unzip Dash to Dock GNOME Shell extension
    unarchive:
      src: "/tmp/dash-to-dock.zip"
      dest: "{{ ansible_env.HOME }}/Downloads"
      remote_src: yes
      extra_opts: --strip-components=1
      creates: "{{ ansible_env.home }}/Downloads/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/metadata.json"

  - name: Enable GNOME Shell extensions
    command: "gnome-extensions install /home{{ ansible_user }}/Downloads/dash-to-dock@micxgx.gmail.com"
    become_user: "{{ ansible_user | default(ansible_env.USER) }}"

  - name: Download yt-dlp
    command: wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp

  - name: Change permissions for yt-dlp
    command: chmod a+rx /usr/local/bin/yt-dlp

  - name: Add Ulauncher repository
    command: sudo add-apt-repository ppa:agornostal/ulauncher

  - name: Update apt cache
    command: sudo apt update

  - name: Install Ulauncher
    command: sudo apt install -y ulauncher
    async: 300

  - name: Clone Vundle.vim repository
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim

  - name: Execute zsh with option 2
    command: expect -c 'spawn zsh; expect "This function can help you wit a few settings that should make your use of shell esier. You can:"; send "2\r"; interact'

  - name: Run command to install Oh My Zsh
    expect:
      command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      responses:
        '(#.*):' : 'yes'

  - name: Run vim command for PluginInstall
    command: vim +PluginInstall +qall


  - name: copy .bashrc file
    copy:
     src: files/bashrc
     dest: '{{ ansible_env.HOME }}/.bashrc'
     owner: '{{ ansible_user }}'
     group: '{{ ansible_user }}'

  - name: copy  .zshrc file
    copy:
     src: files/zshrc
     dest: '{{ ansible_env.HOME}}/.zshrc'
     owner: '{{ ansible_user }}'
     group: '{{ ansible_user }}'


  - name: Copy .vimrc file
    copy:
     src: files/vimrc
     dest: '{{ ansible_env.HOME }}/.vimrc'
     owner: '{{ ansible_user }}'
     group: '{{ ansible_user }}'

  - name: Copy .plugin file
    copy:
     src: files/plugin/plugins.vim
     dest: '{{ ansible_env.HOME }}/.vim/plugins.vim'
     owner: '{{ ansible_user }}'
     group: '{{ ansible_user }}'
